#!/usr/bin/env bash
# Shared PickScribe environment loader.
# Supports the current ~/.config/pickscribe/env path and the old MVP
# ~/.config/voice-cleanup/env path for backward compatibility.
#
# Pre-existing PICKSCRIBE_* environment variables intentionally override values
# from the config file. This lets KDE commands such as
#   PICKSCRIBE_PASTE_CHORD=ctrl-shift-v pickscribe-gui
# create per-shortcut behavior.

set -euo pipefail

PICKSCRIBE_DEFAULT_ENV_FILE="$HOME/.config/pickscribe/env"
PICKSCRIBE_LEGACY_ENV_FILE="$HOME/.config/voice-cleanup/env"
ENV_FILE="${PICKSCRIBE_ENV_FILE:-${VOICE_CLEANUP_ENV_FILE:-$PICKSCRIBE_DEFAULT_ENV_FILE}}"

PICKSCRIBE_KNOWN_ENV_VARS=(
  PICKSCRIBE_PROVIDER
  PICKSCRIBE_MODEL
  PICKSCRIBE_ENDPOINT
  PICKSCRIBE_API_KEY
  PICKSCRIBE_TIMEOUT_SECS
  PICKSCRIBE_TEMPERATURE
  PICKSCRIBE_DEEPSEEK_THINKING
  PICKSCRIBE_TYPE_BACKEND
  PICKSCRIBE_PASTE_METHOD
  PICKSCRIBE_PASTE_CHORD
  PICKSCRIBE_PASTE_DELAY_MS
  PICKSCRIBE_INSTRUCTIONS
  PICKSCRIBE_STATE_DIR
  PICKSCRIBE_RECORDER
  PICKSCRIBE_AUDIO_TARGET
  PICKSCRIBE_WHISPER_MODEL
  PICKSCRIBE_LANGUAGE
  PICKSCRIBE_STT_COMMAND
  PICKSCRIBE_CLEANUP_COMMAND
  PICKSCRIBE_INCREMENTAL_DICTATION
  PICKSCRIBE_KEEP_AUDIO
  PICKSCRIBE_WHISPER_CPP_SRC
  PICKSCRIBE_WHISPER_MODEL_DIR
  PICKSCRIBE_WHISPER_MODEL_NAME
  PICKSCRIBE_AUTO_UPDATE_WHISPER
  PICKSCRIBE_UPDATE_INTERVAL_HOURS
)

declare -A PICKSCRIBE_ENV_OVERRIDES=()
for name in "${PICKSCRIBE_KNOWN_ENV_VARS[@]}"; do
  if [[ -n "${!name+x}" ]]; then
    PICKSCRIBE_ENV_OVERRIDES["$name"]="${!name}"
  fi
done

if [[ -f "$ENV_FILE" ]]; then
  set -a
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  set +a
elif [[ -f "$PICKSCRIBE_LEGACY_ENV_FILE" ]]; then
  set -a
  # shellcheck disable=SC1090
  source "$PICKSCRIBE_LEGACY_ENV_FILE"
  set +a
fi

copy_env() {
  local new_name="$1"
  local old_name="$2"
  if [[ -z "${!new_name+x}" && -n "${!old_name+x}" ]]; then
    export "$new_name=${!old_name}"
  fi
}

copy_env PICKSCRIBE_PROVIDER VOICE_CLEANUP_PROVIDER
copy_env PICKSCRIBE_MODEL VOICE_CLEANUP_MODEL
copy_env PICKSCRIBE_ENDPOINT VOICE_CLEANUP_ENDPOINT
copy_env PICKSCRIBE_API_KEY VOICE_CLEANUP_API_KEY
copy_env PICKSCRIBE_TIMEOUT_SECS VOICE_CLEANUP_TIMEOUT_SECS
copy_env PICKSCRIBE_TEMPERATURE VOICE_CLEANUP_TEMPERATURE
copy_env PICKSCRIBE_DEEPSEEK_THINKING VOICE_CLEANUP_DEEPSEEK_THINKING
copy_env PICKSCRIBE_TYPE_BACKEND VOICE_CLEANUP_TYPE_BACKEND
copy_env PICKSCRIBE_PASTE_METHOD VOICE_CLEANUP_PASTE_METHOD
copy_env PICKSCRIBE_PASTE_CHORD VOICE_CLEANUP_PASTE_CHORD
copy_env PICKSCRIBE_PASTE_DELAY_MS VOICE_CLEANUP_PASTE_DELAY_MS
copy_env PICKSCRIBE_INSTRUCTIONS VOICE_CLEANUP_INSTRUCTIONS

copy_env PICKSCRIBE_STATE_DIR VOICE_FLOW_STATE_DIR
copy_env PICKSCRIBE_RECORDER VOICE_FLOW_RECORDER
copy_env PICKSCRIBE_AUDIO_TARGET VOICE_FLOW_AUDIO_TARGET
copy_env PICKSCRIBE_WHISPER_MODEL VOICE_FLOW_WHISPER_MODEL
copy_env PICKSCRIBE_LANGUAGE VOICE_FLOW_LANGUAGE
copy_env PICKSCRIBE_STT_COMMAND VOICE_FLOW_STT_COMMAND
copy_env PICKSCRIBE_CLEANUP_COMMAND VOICE_FLOW_CLEANUP_COMMAND
copy_env PICKSCRIBE_KEEP_AUDIO VOICE_FLOW_KEEP_AUDIO
copy_env PICKSCRIBE_WHISPER_CPP_SRC VOICE_FLOW_WHISPER_CPP_SRC
copy_env PICKSCRIBE_WHISPER_MODEL_DIR VOICE_FLOW_WHISPER_MODEL_DIR
copy_env PICKSCRIBE_WHISPER_MODEL_DIR VOICE_FLOW_MODEL_DIR
copy_env PICKSCRIBE_WHISPER_MODEL_NAME VOICE_FLOW_WHISPER_MODEL_NAME
copy_env PICKSCRIBE_WHISPER_MODEL_NAME VOICE_FLOW_MODEL_NAME
copy_env PICKSCRIBE_AUTO_UPDATE_WHISPER VOICE_FLOW_AUTO_UPDATE_WHISPER
copy_env PICKSCRIBE_UPDATE_INTERVAL_HOURS VOICE_FLOW_UPDATE_INTERVAL_HOURS

for name in "${!PICKSCRIBE_ENV_OVERRIDES[@]}"; do
  export "$name=${PICKSCRIBE_ENV_OVERRIDES[$name]}"
done
